/**
 * rentalSeeder.service.ts
 *
 * Automatic, Idempotent Seeder for VITO Rental Hubs & Demo Vehicles
 *
 * Runs automatically on backend startup. If hubs/vehicles exist, skips or updates
 * cleanly without duplicating records.
 */

import User from '../models/User.model';
import RentalHub from '../models/RentalHub.model';
import Vehicle from '../models/Vehicle.model';

export const SEED_HUBS = [
  {
    name: 'Kanpur Central Hub',
    code: 'HUB-KNP',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    country: 'India',
    address: 'Platform 1 Exit, Kanpur Central Railway Station Road, Kanpur, UP 208001',
    location: { lat: 26.4499, lng: 80.3319 },
    serviceRadiusKm: 40,
    aliases: ['kanpur', 'jajmau', 'kalyanpur', 'shyam nagar', 'civil lines', 'iit kanpur', 'chakeri', 'rawatpur', 'mall road', 'cantt', 'govind nagar', 'kidwai nagar', 'barra'],
    pickupSupported: true,
    deliverySupported: true,
    oneWayReturnSupported: true,
    supportedOneWayReturnHubCodes: ['HUB-DEL', 'HUB-JAI', 'HUB-BOM'],
    isDemo: true,
    status: 'ACTIVE',
  },
  {
    name: 'Delhi NCR Central Hub',
    code: 'HUB-DEL',
    city: 'Delhi NCR',
    state: 'Delhi',
    country: 'India',
    address: 'Aerocity Metro Station Hub, New Delhi 110037',
    location: { lat: 28.6315, lng: 77.2167 },
    serviceRadiusKm: 50,
    aliases: ['delhi', 'new delhi', 'noida', 'gurugram', 'gurgaon', 'ghaziabad', 'faridabad', 'cp', 'connaught place', 'aerocity', 'igi airport', 'saket', 'dwarka', 'south extension'],
    pickupSupported: true,
    deliverySupported: true,
    oneWayReturnSupported: true,
    supportedOneWayReturnHubCodes: ['HUB-JAI', 'HUB-KNP', 'HUB-BOM', 'HUB-BLR'],
    isDemo: true,
    status: 'ACTIVE',
  },
  {
    name: 'Mumbai Airport & Central Hub',
    code: 'HUB-BOM',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    address: 'Terminal 2 Car Park P4, Chhatrapati Shivaji Maharaj International Airport, Mumbai 400099',
    location: { lat: 19.0760, lng: 72.8777 },
    serviceRadiusKm: 45,
    aliases: ['mumbai', 'andheri', 'bandra', 'colaba', 'thane', 'navi mumbai', 'powai', 'juhu', 'borivali', 'dadar', 'kurla', 'worli', 'bkc'],
    pickupSupported: true,
    deliverySupported: true,
    oneWayReturnSupported: true,
    supportedOneWayReturnHubCodes: ['HUB-BLR', 'HUB-HYD', 'HUB-DEL', 'HUB-JAI'],
    isDemo: true,
    status: 'ACTIVE',
  },
  {
    name: 'Bengaluru Tech Hub',
    code: 'HUB-BLR',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    address: 'Indiranagar 100ft Road Mobility Centre, Bengaluru 560038',
    location: { lat: 12.9716, lng: 77.5946 },
    serviceRadiusKm: 40,
    aliases: ['bengaluru', 'bangalore', 'koramangala', 'indiranagar', 'whitefield', 'electronic city', 'hsr layout', 'hebbal', 'marathahalli', 'jayanagar', 'airport road'],
    pickupSupported: true,
    deliverySupported: true,
    oneWayReturnSupported: true,
    supportedOneWayReturnHubCodes: ['HUB-HYD', 'HUB-BOM', 'HUB-DEL'],
    isDemo: true,
    status: 'ACTIVE',
  },
  {
    name: 'Hyderabad City Hub',
    code: 'HUB-HYD',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    address: 'HITEC City Cyber Towers Exit, Madhapur, Hyderabad 500081',
    location: { lat: 17.3850, lng: 78.4867 },
    serviceRadiusKm: 40,
    aliases: ['hyderabad', 'hitec city', 'gachibowli', 'jubilee hills', 'banjara hills', 'secunderabad', 'madhapur', 'kondapur', 'kukatpally'],
    pickupSupported: true,
    deliverySupported: true,
    oneWayReturnSupported: true,
    supportedOneWayReturnHubCodes: ['HUB-BLR', 'HUB-BOM'],
    isDemo: true,
    status: 'ACTIVE',
  },
  {
    name: 'Jaipur Heritage Hub',
    code: 'HUB-JAI',
    city: 'Jaipur',
    state: 'Rajasthan',
    country: 'India',
    address: 'MI Road Central Plaza, C-Scheme, Jaipur 302001',
    location: { lat: 26.9124, lng: 75.7873 },
    serviceRadiusKm: 35,
    aliases: ['jaipur', 'c scheme', 'malviya nagar', 'mansarovar', 'vaishali nagar', 'pink city', 'amer', 'tonk road', 'raja park'],
    pickupSupported: true,
    deliverySupported: true,
    oneWayReturnSupported: true,
    supportedOneWayReturnHubCodes: ['HUB-DEL', 'HUB-KNP', 'HUB-BOM'],
    isDemo: true,
    status: 'ACTIVE',
  },
];

export async function autoSeedRentals(): Promise<void> {
  try {
    // 1. Ensure Fleet Operations user exists
    let fleetHost = await User.findOne({ email: 'fleet@vito.com' });
    if (!fleetHost) {
      fleetHost = await User.create({
        name: 'VITO Fleet Operations',
        email: 'fleet@vito.com',
        phone: '+919000000001',
        passwordHash: '$2a$10$abcdefghijklmnopqrstuvwxyz123456',
        role: 'partner',
        licenceVerified: true,
        identityVerified: true,
      });
    }

    // 2. Upsert Rental Hubs (idempotent)
    const hubMap: Record<string, any> = {};
    for (const hubData of SEED_HUBS) {
      const hub = await RentalHub.findOneAndUpdate(
        { code: hubData.code },
        { $set: hubData },
        { upsert: true, new: true }
      );
      hubMap[hubData.code] = hub;
    }

    // 3. Check if demo vehicles already exist
    const demoVehicleCount = await Vehicle.countDocuments({ isDemo: true });
    if (demoVehicleCount >= 12) {
      // Already fully seeded
      return;
    }

    // 4. Seed rich fleet of demo vehicles for all hubs
    const FLEET_INVENTORY = [
      // ─── KANPUR INVENTORY ────────────────────────────────────────────────
      {
        make: 'Toyota',
        vehicleModel: 'Innova Crysta',
        year: 2024,
        name: 'Toyota Innova Crysta ZX',
        registrationNumber: 'UP-78-TX-9901',
        category: 'muv',
        fuelType: 'diesel',
        transmission: 'automatic',
        seats: 7,
        pricePerDay: 3200,
        depositAmount: 10000,
        images: [
          'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&q=80',
          'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80',
          'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80',
        ],
        location: hubMap['HUB-KNP'].location,
        city: 'Kanpur',
        hubId: hubMap['HUB-KNP']._id,
        hubCode: 'HUB-KNP',
        hubName: 'Kanpur Central Hub',
        status: 'VERIFIED',
        deliveryAvailable: true,
        oneWayRentalSupported: true,
        isDemo: true,
        rating: 4.88,
        totalRatings: 142,
        totalRentals: 142,
        features: ['Captain Seats', 'Rear AC Vents', 'Apple CarPlay & Android Auto', 'Cruise Control', '7 Airbags', 'Emergency SOS Kit'],
        mileagePolicy: '250 km/day included, ₹12/km beyond',
        hostName: 'ABC Rentals',
        hostRating: 4.88,
        hostCompletedRentals: 142,
        ownerId: fleetHost._id,
      },
      {
        make: 'Maruti Suzuki',
        vehicleModel: 'Swift',
        year: 2023,
        name: 'Maruti Swift ZXi (Kanpur)',
        registrationNumber: 'UP-78-AB-1024',
        category: 'hatchback',
        fuelType: 'petrol',
        transmission: 'manual',
        seats: 5,
        pricePerDay: 1299,
        depositAmount: 2000,
        images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&q=80'],
        location: hubMap['HUB-KNP'].location,
        city: 'Kanpur',
        hubId: hubMap['HUB-KNP']._id,
        hubCode: 'HUB-KNP',
        hubName: 'Kanpur Central Hub',
        status: 'VERIFIED',
        deliveryAvailable: true,
        oneWayRentalSupported: true,
        isDemo: true,
        rating: 4.8,
        totalRatings: 42,
        totalRentals: 42,
        features: ['AC', 'Bluetooth Audio', 'USB Charging', 'Reverse Parking Sensors', 'Dual Airbags'],
        mileagePolicy: '250 km/day free, ₹9/km beyond',
        hostName: 'CityDrive Mobility',
        hostRating: 4.85,
        hostCompletedRentals: 85,
        ownerId: fleetHost._id,
      },
      {
        make: 'Hyundai',
        vehicleModel: 'Creta',
        year: 2024,
        name: 'Hyundai Creta SX (Kanpur)',
        registrationNumber: 'UP-78-CD-2048',
        category: 'suv',
        fuelType: 'petrol',
        transmission: 'automatic',
        seats: 5,
        pricePerDay: 2499,
        depositAmount: 4500,
        images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80'],
        location: hubMap['HUB-KNP'].location,
        city: 'Kanpur',
        hubId: hubMap['HUB-KNP']._id,
        hubCode: 'HUB-KNP',
        hubName: 'Kanpur Central Hub',
        status: 'VERIFIED',
        deliveryAvailable: true,
        oneWayRentalSupported: true,
        isDemo: true,
        rating: 4.9,
        totalRatings: 68,
        totalRentals: 68,
        features: ['Panoramic Sunroof', 'Bose Sound', 'Wireless Charging', 'Cruise Control', 'Ventilated Seats'],
        mileagePolicy: '300 km/day free, ₹12/km beyond',
        hostName: 'VITO Fleet Kanpur',
        hostRating: 4.85,
        hostCompletedRentals: 85,
        ownerId: fleetHost._id,
      },
      {
        make: 'Mahindra',
        vehicleModel: 'Thar',
        year: 2024,
        name: 'Mahindra Thar 4x4 Hardtop',
        registrationNumber: 'UP-78-EF-4096',
        category: 'suv',
        fuelType: 'diesel',
        transmission: 'automatic',
        seats: 4,
        pricePerDay: 3299,
        depositAmount: 6000,
        images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80'],
        location: hubMap['HUB-KNP'].location,
        city: 'Kanpur',
        hubId: hubMap['HUB-KNP']._id,
        hubCode: 'HUB-KNP',
        hubName: 'Kanpur Central Hub',
        status: 'VERIFIED',
        deliveryAvailable: true,
        oneWayRentalSupported: true,
        isDemo: true,
        rating: 4.95,
        totalRatings: 52,
        totalRentals: 52,
        features: ['4x4 Drivetrain', 'Touchscreen Infotainment', 'Convertible Hardtop', 'Hill Hold Assist'],
        mileagePolicy: '350 km/day free, ₹14/km beyond',
        hostName: 'VITO Fleet Kanpur',
        hostRating: 4.85,
        hostCompletedRentals: 85,
        ownerId: fleetHost._id,
      },
      {
        make: 'Honda',
        vehicleModel: 'City',
        year: 2023,
        name: 'Honda City ZX CVT (Kanpur)',
        registrationNumber: 'UP-78-GH-8192',
        category: 'sedan',
        fuelType: 'petrol',
        transmission: 'automatic',
        seats: 5,
        pricePerDay: 1999,
        depositAmount: 3500,
        images: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80'],
        location: hubMap['HUB-KNP'].location,
        city: 'Kanpur',
        hubId: hubMap['HUB-KNP']._id,
        hubCode: 'HUB-KNP',
        hubName: 'Kanpur Central Hub',
        status: 'VERIFIED',
        deliveryAvailable: true,
        oneWayRentalSupported: true,
        isDemo: true,
        rating: 4.75,
        totalRatings: 34,
        totalRentals: 34,
        features: ['Sunroof', 'LaneWatch Camera', 'Leather Upholstery', 'Apple CarPlay & Android Auto'],
        mileagePolicy: '250 km/day free, ₹11/km beyond',
        hostName: 'VITO Fleet Kanpur',
        hostRating: 4.85,
        hostCompletedRentals: 85,
        ownerId: fleetHost._id,
      },

      // ─── DELHI NCR INVENTORY ─────────────────────────────────────────────
      {
        make: 'Maruti Suzuki',
        vehicleModel: 'Swift',
        year: 2023,
        name: 'Maruti Swift VXi (Delhi)',
        registrationNumber: 'DL-01-AB-1234',
        category: 'hatchback',
        fuelType: 'petrol',
        transmission: 'manual',
        seats: 5,
        pricePerDay: 1299,
        depositAmount: 2000,
        images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&q=80'],
        location: hubMap['HUB-DEL'].location,
        city: 'Delhi NCR',
        hubId: hubMap['HUB-DEL']._id,
        hubCode: 'HUB-DEL',
        hubName: 'Delhi NCR Central Hub',
        status: 'VERIFIED',
        deliveryAvailable: true,
        oneWayRentalSupported: true,
        isDemo: true,
        rating: 4.7,
        totalRatings: 88,
        totalRentals: 88,
        features: ['AC', 'Bluetooth', 'USB Fast Charger', 'Reverse Camera'],
        mileagePolicy: '200 km/day free, ₹10/km beyond',
        hostName: 'VITO Fleet Delhi',
        hostRating: 4.9,
        hostCompletedRentals: 210,
        ownerId: fleetHost._id,
      },
      {
        make: 'Hyundai',
        vehicleModel: 'Creta',
        year: 2024,
        name: 'Hyundai Creta Turbo DCT (Delhi)',
        registrationNumber: 'DL-03-CD-5678',
        category: 'suv',
        fuelType: 'petrol',
        transmission: 'automatic',
        seats: 5,
        pricePerDay: 2499,
        depositAmount: 5000,
        images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80'],
        location: hubMap['HUB-DEL'].location,
        city: 'Delhi NCR',
        hubId: hubMap['HUB-DEL']._id,
        hubCode: 'HUB-DEL',
        hubName: 'Delhi NCR Central Hub',
        status: 'VERIFIED',
        deliveryAvailable: true,
        oneWayRentalSupported: true,
        isDemo: true,
        rating: 4.92,
        totalRatings: 115,
        totalRentals: 115,
        features: ['Sunroof', 'GPS Navigation', 'ADAS Level 2', 'Bose Sound', 'Wireless Charger'],
        mileagePolicy: '250 km/day free, ₹12/km beyond',
        hostName: 'VITO Fleet Delhi',
        hostRating: 4.9,
        hostCompletedRentals: 210,
        ownerId: fleetHost._id,
      },
      {
        make: 'Tata',
        vehicleModel: 'Nexon EV',
        year: 2024,
        name: 'Tata Nexon EV Max (Delhi)',
        registrationNumber: 'DL-01-EV-9999',
        category: 'ev',
        fuelType: 'electric',
        transmission: 'automatic',
        seats: 5,
        pricePerDay: 2799,
        depositAmount: 5500,
        images: ['https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&q=80'],
        location: hubMap['HUB-DEL'].location,
        city: 'Delhi NCR',
        hubId: hubMap['HUB-DEL']._id,
        hubCode: 'HUB-DEL',
        hubName: 'Delhi NCR Central Hub',
        status: 'VERIFIED',
        deliveryAvailable: true,
        oneWayRentalSupported: true,
        isDemo: true,
        rating: 4.88,
        totalRatings: 64,
        totalRentals: 64,
        features: ['Free Fast Charging at VITO Hubs', '312km Real Range', 'Regen Braking', 'Sunroof'],
        mileagePolicy: 'Unlimited electric charging at VITO hubs',
        hostName: 'VITO Fleet Delhi',
        hostRating: 4.9,
        hostCompletedRentals: 210,
        ownerId: fleetHost._id,
      },
      {
        make: 'Toyota',
        vehicleModel: 'Innova Crysta',
        year: 2023,
        name: 'Toyota Innova Crysta 7-Seater',
        registrationNumber: 'DL-02-XY-7777',
        category: 'muv',
        fuelType: 'diesel',
        transmission: 'automatic',
        seats: 7,
        pricePerDay: 3499,
        depositAmount: 7000,
        images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80'],
        location: hubMap['HUB-DEL'].location,
        city: 'Delhi NCR',
        hubId: hubMap['HUB-DEL']._id,
        hubCode: 'HUB-DEL',
        hubName: 'Delhi NCR Central Hub',
        status: 'VERIFIED',
        deliveryAvailable: true,
        oneWayRentalSupported: true,
        isDemo: true,
        rating: 4.95,
        totalRatings: 140,
        totalRentals: 140,
        features: ['7 Captain Seats', 'Roof AC Vents', 'Cruise Control', 'Spacious Boot'],
        mileagePolicy: '300 km/day free, ₹14/km beyond',
        hostName: 'VITO Fleet Delhi',
        hostRating: 4.9,
        hostCompletedRentals: 210,
        ownerId: fleetHost._id,
      },

      // ─── MUMBAI INVENTORY ────────────────────────────────────────────────
      {
        make: 'Honda',
        vehicleModel: 'City',
        year: 2023,
        name: 'Honda City Automatic (Mumbai)',
        registrationNumber: 'MH-02-EE-3344',
        category: 'sedan',
        fuelType: 'petrol',
        transmission: 'automatic',
        seats: 5,
        pricePerDay: 1999,
        depositAmount: 3500,
        images: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80'],
        location: hubMap['HUB-BOM'].location,
        city: 'Mumbai',
        hubId: hubMap['HUB-BOM']._id,
        hubCode: 'HUB-BOM',
        hubName: 'Mumbai Airport & Central Hub',
        status: 'VERIFIED',
        deliveryAvailable: true,
        oneWayRentalSupported: true,
        isDemo: true,
        rating: 4.82,
        totalRatings: 59,
        totalRentals: 59,
        features: ['AC', 'Bluetooth', 'Touchscreen', 'Reverse Camera'],
        mileagePolicy: '200 km/day free, ₹12/km beyond',
        hostName: 'VITO Fleet Mumbai',
        hostRating: 4.8,
        hostCompletedRentals: 95,
        ownerId: fleetHost._id,
      },
      {
        make: 'Kia',
        vehicleModel: 'Seltos',
        year: 2024,
        name: 'Kia Seltos GTX+ (Mumbai)',
        registrationNumber: 'MH-02-FF-5566',
        category: 'suv',
        fuelType: 'petrol',
        transmission: 'automatic',
        seats: 5,
        pricePerDay: 2299,
        depositAmount: 4500,
        images: ['https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80'],
        location: hubMap['HUB-BOM'].location,
        city: 'Mumbai',
        hubId: hubMap['HUB-BOM']._id,
        hubCode: 'HUB-BOM',
        hubName: 'Mumbai Airport & Central Hub',
        status: 'VERIFIED',
        deliveryAvailable: true,
        oneWayRentalSupported: true,
        isDemo: true,
        rating: 4.87,
        totalRatings: 48,
        totalRentals: 48,
        features: ['Bose Audio', 'Sunroof', 'Wireless Charging', '360 Camera'],
        mileagePolicy: '250 km/day free, ₹12/km beyond',
        hostName: 'VITO Fleet Mumbai',
        hostRating: 4.8,
        hostCompletedRentals: 95,
        ownerId: fleetHost._id,
      },

      // ─── BENGALURU INVENTORY ─────────────────────────────────────────────
      {
        make: 'Kia',
        vehicleModel: 'Seltos',
        year: 2024,
        name: 'Kia Seltos HTX (Bengaluru)',
        registrationNumber: 'KA-01-BL-1122',
        category: 'suv',
        fuelType: 'petrol',
        transmission: 'automatic',
        seats: 5,
        pricePerDay: 2299,
        depositAmount: 4500,
        images: ['https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80'],
        location: hubMap['HUB-BLR'].location,
        city: 'Bengaluru',
        hubId: hubMap['HUB-BLR']._id,
        hubCode: 'HUB-BLR',
        hubName: 'Bengaluru Tech Hub',
        status: 'VERIFIED',
        deliveryAvailable: true,
        oneWayRentalSupported: true,
        isDemo: true,
        rating: 4.89,
        totalRatings: 73,
        totalRentals: 73,
        features: ['Panoramic Sunroof', 'Bose Sound', 'Wireless Charging'],
        mileagePolicy: '250 km/day free, ₹11/km beyond',
        hostName: 'VITO Fleet Bengaluru',
        hostRating: 4.85,
        hostCompletedRentals: 75,
        ownerId: fleetHost._id,
      },

      // ─── JAIPUR INVENTORY ────────────────────────────────────────────────
      {
        make: 'Mahindra',
        vehicleModel: 'Thar',
        year: 2024,
        name: 'Mahindra Thar 4x4 (Jaipur)',
        registrationNumber: 'RJ-14-TH-9900',
        category: 'suv',
        fuelType: 'diesel',
        transmission: 'automatic',
        seats: 4,
        pricePerDay: 3499,
        depositAmount: 6000,
        images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80'],
        location: hubMap['HUB-JAI'].location,
        city: 'Jaipur',
        hubId: hubMap['HUB-JAI']._id,
        hubCode: 'HUB-JAI',
        hubName: 'Jaipur Heritage Hub',
        status: 'VERIFIED',
        deliveryAvailable: true,
        oneWayRentalSupported: true,
        isDemo: true,
        rating: 4.94,
        totalRatings: 61,
        totalRentals: 61,
        features: ['4x4 Off-Road Drive', 'All-Terrain Tyres', 'Cruise Control', 'Touchscreen'],
        mileagePolicy: '300 km/day free, ₹14/km beyond',
        hostName: 'VITO Fleet Jaipur',
        hostRating: 4.9,
        hostCompletedRentals: 80,
        ownerId: fleetHost._id,
      },
    ];

    // Delete existing demo vehicles, documents, and bookings, then insert fresh idempotent ones
    const RentalDocument = (await import('../models/RentalDocument.model')).default;
    const RentalBooking = (await import('../models/RentalBooking.model')).default;
    await RentalDocument.deleteMany({ ownerType: 'VEHICLE', isDemo: true });
    await RentalBooking.deleteMany({ isDemo: true });
    await Vehicle.deleteMany({ isDemo: true });
    const insertedVehicles = await Vehicle.insertMany(FLEET_INVENTORY);

    // Seed vehicle compliance documents (RC, Insurance, PUC, Fitness, Permit)
    const { seedVehicleDocuments } = await import('./rentalDocument.service');
    for (const v of insertedVehicles) {
      await seedVehicleDocuments(v._id, v.registrationNumber);
    }

    // Update fleet count on hubs
    for (const code of Object.keys(hubMap)) {
      const count = await Vehicle.countDocuments({ hubCode: code, status: 'VERIFIED' });
      await RentalHub.updateOne({ code }, { totalFleetCount: count });
    }

    console.log(`✅ VITO Rental Hubs, Demo Fleet (${insertedVehicles.length} vehicles), and Compliance Documents auto-seeded successfully!`);
  } catch (error) {
    console.error('❌ Error in autoSeedRentals:', error);
  }
}
